### ISSUE TITLE
Fix this project

### ISSUE THREAD

**Issue by hayzey** [hayzey/simpleweather#12]
Haven't touched it in over year, should probably redo it.

**Comment by andyhe886** [comment]
is it suppose to output something when i input my city in the search bar?

**Comment by htrivedi04** [comment]
Looks good to me.. what exactly needs to be fixed here ?? Please elaborate the issue !!

**Comment by thetomja** [comment]
To be quite honest, I was just curious to see if tagging a project with "Hacktoberfest" would grab someone's attention. That being said, if someone out there feels like using this code in their own project or forking it for fun or whatever, go for it.

**Comment by over-engineer** [comment]
Hello @hayzey, adding the "Hacktoberfest" label certainly grabbed my attention 😛 

I'd love to "fix" this project by tackling with most of the issues you have opened!

Also, maybe moving to ES6 and removing the jQuery dependency, if that's okay.
